source 'https://www.rubygems.org'

gem 'appium_lib',			'~> 10.3.1'
gem 'cucumber',        '~> 3.1.2'
gem 'test-unit',			'~> 2.5'
gem 'page-object',			'~> 2.2.4'
gem 'watir',				'~> 6.16.5'
gem 'selenium-webdriver',	'~> 3.142.3'
gem 'watir-webdriver',		'~> 0.9.9'
gem 'cucumber-rails',		:require => false
gem 'res',					'~> 1.2'
gem 'os'
gem 'headless',             '~> 2.3'
gem 'sauce_whisk', '~> 0.2.1'
gem 'test_object_test_result_watcher', '~> 1.1.3'
gem 'pry'
gem 'pry-nav'
gem 'rake'
gem'rubocop', require: false
gem 'rspec', '~> 3.9'
gem 'report_builder', '~> 1.8'
gem 'cucumber-report-format', '~> 0.0.3'
gem 'browserstack-local'
gem 'aws-sdk-s3', '~> 1.94'
gem 'dotenv', '~> 2.1', '>= 2.1.1'
