source 'https://www.rubygems.org'

gem 'appium_lib',			'~> 10.3.1'
gem 'cucumber',        '~> 3.1.2'
gem 'test-unit',			'~> 2.5'
gem 'pry'
gem 'pry-nav'
gem 'report_builder', '~> 1.8'
gem 'cucumber-report-format', '~> 0.0.3'
gem 'aws-sdk-s3', '~> 1.94'
gem 'dotenv', '~> 2.1', '>= 2.1.1'
