env:
  prod:
    username: 'software-devs@sohohouse.com'
    password: 'left mysterious silk share'
    name: 'Devs'
    house: 'Paris'
    profile: 'Every House'
  stag:
    username: 'nigel.spooner@sohohouse.com'
    password: 'password'
    name: 'SFFactory'
    house: 'Shoreditch House'
    profile: 'Local'
