env:
  prod:
    Enter_Email:
    name: 'Ravi Kumar'
    house: '40 Greek Street'
    profile: 'Every House'
  stag:
    mobile_automation@sohohouse.com:
      name: 'SFFactory TestUser'
      house: 'Babington House'
      profile: 'Every House'
    manikanth.erukulla@sohohouse.com:
      name: 'Manikanth'
      house: 'Little Beach House Barcelona'
      profile: 'Every House'
    mobile_android_automation@sohohouse.com:
      name: 'SFFactory TestUser'
      house: 'Babington House'
      profile: 'Every House'
