env:
  prod:
    username: 'software-devs@sohohouse.com'
    password: 'left mysterious silk share'
    name: 'Devs'
    house: 'Paris'
    profile: 'Every House'
  stag:
    mobile_automation@sohohouse.com:
      name: 'SFFactory'
      house: 'Little Beach House Barcelona'
      profile: 'Every House'
    manikanth.erukulla@sohohouse.com:
      name: 'Manikanth'
      house: 'Little Beach House Barcelona'
      profile: 'Every House'