env:
  prod:
    Enter_Email:
    name: 'Ravi Kumar'
    house: '40 Greek Street'
    profile: 'Every House'
  stag:
    mobile_automation@sohohouse.com:
      name: 'SFFactory TestUser'
      house: 'Babington House'
      profile: 'Every House'
    ios_changepassword@example.com:
      name: 'SFFactory'
      house: 'Babington House'
      profile: 'Every House'
    change_password_android@example.com:
      name: 'SFFactory'
      house: 'Babington House'
      profile: 'Every House'
    manikanth.erukulla@sohohouse.com:
      name: 'Manikanth'
      house: 'Little Beach House Barcelona'
      profile: 'Every House'
    mobile_android_automation@sohohouse.com:
      name: 'SFFactory TestUser'
      house: 'Babington House'
      profile: 'Every House'
    new_test_v@example.com:
      name: 'SFFactory'
      house: 'Little Beach House Barcelona'
      profile: 'Every House'
