ios:
  iphoneX:
    stag:
      real:
        udid: XXXXX-XXXXXX-XXXXXXX-XXXXXXXXX
        platform_version: 12.2
      simulator:
        udid: E30DC005-BF83-4116-A825-BAE853E45284
        platform_version: 13.2
    prod:
      real:
        udid: XXXXX-XXXXXX-XXXXXXX-XXXXXXXXX
        platform_version: 12.2
      simulator:
        udid: D6DBBF52-3671-4177-9D62-4214E82E1C9E
        platform_version: 12.2
  iphone6:
    stag:
      real:
        udid: XXXXX-XXXXXX-XXXXXXX-XXXXXXXXX
        platform_version: 12.3
      simulator:
        udid: B377173E-13A4-4DA3-86A3-220AE2690544
        platform_version: 12.2
    prod:
      real:
        udid: ad6ce140e9909f9a6907504e929626df7301fde3
        platform_version: 12.2
      simulator:
        udid: D6DBBF52-3671-4177-9D62-4214E82E1C9E
        platform_version: 12.2
  bundle:
    stag: com.sohohouse.houseseven.staging
    prod: com.sohohouse.houseseven
  app_path:
    stag: /Users/manikanth.erukulla/apps/ios/stag/DigitalHouse.app
    prod: /Users/manikanth.erukulla/apps/ios/prod/DigitalHouse.app
