ios:
  iphoneX:
    stag:
      real:
        udid: 00008020-000E3D9A0A86002E
        platform_version: 12.2
      simulator:
        udid: 0FFA9478-B85D-42BF-AFD5-37C60984F4A7
        platform_version: 13.3
    prod:
      real:
        udid: XXXXX-XXXXXX-XXXXXXX-XXXXXXXXX
        platform_version: 12.2
      simulator:
        udid: D6DBBF52-3671-4177-9D62-4214E82E1C9E
        platform_version: 12.2
  iphone6:
    stag:
      real:
        udid: XXXXX-XXXXXX-XXXXXXX-XXXXXXXXX
        platform_version: 12.3
      simulator:
        udid: B377173E-13A4-4DA3-86A3-220AE2690544
        platform_version: 12.2
    prod:
      real:
        udid: ad6ce140e9909f9a6907504e929626df7301fde3
        platform_version: 12.2
      simulator:
        udid: D6DBBF52-3671-4177-9D62-4214E82E1C9E
        platform_version: 12.2
  bundle:
    stag: com.sohohouse.enterprise.staging
    prod: com.sohohouse.houseseven
  app_path:
    stag: /Users/XXXXXXXXXXX/XXXXXXXXXX/DigitalHouse.app
    prod: /Users/XXXXXXXXXXX/XXXXXXXXXX/DigitalHouse.app
