data:
  run-id: '1'
  event:
    name: 'Member events test'
  screen:
    name: 'Screening Event Automation'
  Gym:
    name: 'Gym Event Automation'
  profile:
    profile1:
      profession: 'software'
      industry: 'Art'
      city: 'Manhattan'
      about-me: 'I am the king of this jungle'
      chat: 'Anything you wish to chat'
      interest1: 'Ice hockey'
      interest2: 'Inline skating'
      website: 'https://www.geeksforgeeks.org/'
      instagram: '@sohohouse'
      twitter: '@sohohouse'
      linkedin: 'https://linkedin.com/in/sohohouse'
      spotify: 'https://open.spotify.com/user/sohohouse'
      youtube: 'https://www.youtube.com/user/sohohouse'
    profile2:
      profession: 'Buyer'
      industry: 'Beauty'
      city: 'New Jersey'
      about-me: 'Fantastic'
      chat: 'Anything'
      interest1: 'Ice skating'
      interest2: 'Inline skating'
      website: 'https://www.oops.org/'
      instagram: '@amazing'
      twitter: '@amazing'
      linkedin: 'https://linkedin.com/in/automtion'
      spotify: 'https://open.spotify.com/user/automation'
      youtube: 'https://www.youtube.com/user/automation'