data:
  run-id: '1'
  event:
    paid-event: 'Mobile Automation - Do not use'
    free-event: 'Mobile Automation-Free event-Do not use'
  screen:
    paid-event: 'The Lion King'
    free-event: 'Film Thumb Test - The Asphalt Jungle'
  Gym:
    paid-event: 'Mobile-Gym Event-Do not use'
    free-event: 'Mobile Automation-Free event-Do not use'
  active-site:
    member-event: 'Soho Warehouse - Mobile Aut...'
    gym-event: 'Soho Warehouse - Gym event ...'
  my-planner:
    member-event: 'My Planner-Member-Mobile new'
    gym-event: 'My Planner-Gym-Mobile testing'
  profile:
    profile1:
      profession: 'Software Analyst'
      industry: 'Art'
      city: 'Manhattan'
      about-me: 'I am the king of this jungle'
      chat: 'Anything'
      interest1: ['Travel->Outdoor activities','Fashion->Beauty','Travel->Water sports']
      website: 'https://www.geeksforgeeks.org/'
      instagram: '@sohohouse'
      twitter: '@sohohouse'
      linkedin: 'https://linkedin.com/in/sohohouse'
      spotify: 'https://open.spotify.com/user/sohohouse'
      youtube: 'https://www.youtube.com/user/sohohouse'
    profile2:
      profession: 'Buyer'
      industry: 'Beauty'
      city: 'New Jersey'
      about-me: 'Fantastic'
      chat: 'Anything'
      interest1: 'Ice skating'
      website: 'https://www.oops.org/'
      instagram: '@amazing'
      twitter: '@amazing'
      linkedin: 'https://linkedin.com/in/automation'
      spotify: 'https://open.spotify.com/user/automation'
      youtube: 'https://www.youtube.com/user/automation'
  non-active-local: 'app.non.active.shw.local@example.com'
  non-active-every: 'app.non.active.every.local@example.com'
  active-local: 'app.active.shw.local@example.com'
  active-every: 'app.active.every.local@example.com'
  active-plus-local: 'app.active-plus.shw.local@example.com'
  chasing: 'chasing.sample@sffactory.com'
  suspended: 'suspended.sample@sffactory.com'
  frozen: 'frozen.sample@sffactory.com'
  expired: 'expired.sample@sffactory.com'
  test-connect: 'new_test_v@example.com'
  test-user: 'mobile_automation@sohohouse.com'
  active-plus-every: 'app.active-plus.every.local@example.com'
  active-members-only-status: 'ACTIVE MEMBERS ONLY'
  house-members-only-status: 'HOUSE MEMBERS ONLY'
  change-password-ios: 'ios_changepassword@example.com'
  change-password-android: 'change_password_android@example.com'
  need_signout: ["User updates their password","User reverts their password","User login with different accounts and verifies message","Validate open users profile by clicking on profile picture", "Verify leaving a live stream room confirmation pop up and post call connection", "Verify Call history and My connections and Block member functionality", "Verify messages from side bar navigation"]
  need_separate_sign_in: ["User login with different accounts and verifies message","Validate open users profile by clicking on profile picture", "Verify leaving a live stream room confirmation pop up and post call connection", "Verify Call history and My connections and Block member functionality", "Verify messages from side bar navigation"]
  email-id:
    ios:
      User updates their password: 'ios_changepassword@example.com'
      User reverts their password: 'ios_changepassword@example.com'
      chasing: 'chasing.sample@sffactory.com'
      suspended: 'suspended.sample@sffactory.com'
      frozen: 'frozen.sample@sffactory.com'
      expired: 'expired.sample@sffactory.com'
    android:
      User updates their password: 'change_password_android@example.com'
      User reverts their password: 'change_password_android@example.com'
      chasing: 'chasing.sample@sffactory.com'
      suspended: 'suspended.sample@sffactory.com'
      frozen: 'frozen.sample@sffactory.com'
      expired: 'expired.sample@sffactory.com'
