data:
  run-id: '1'
  event:
    paid-event: 'Mobile Automation - Do not use'
    free-event: 'Mobile Automation-Free event-Do not use'
  screen:
    paid-event: 'The Lion King'
    free-event: 'Film Thumb Test - The Asphalt Jungle'
  Gym:
    paid-event: 'Mobile-Gym Event-Do not use'
    free-event: 'Mobile Automation-Free event-Do not use'
  active-site:
    member-event: 'Soho Warehouse - Mobile Aut...'
    gym-event: 'Soho Warehouse - Gym event ...'
  profile:
    profile1:
      profession: 'software'
      industry: 'Art'
      city: 'Manhattan'
      about-me: 'I am the king of this jungle'
      chat: 'Anything you wish to chat'
      interest1: 'Ice hockey'
      interest2: 'Inline skating'
      website: 'https://www.geeksforgeeks.org/'
      instagram: '@sohohouse'
      twitter: '@sohohouse'
      linkedin: 'https://linkedin.com/in/sohohouse'
      spotify: 'https://open.spotify.com/user/sohohouse'
      youtube: 'https://www.youtube.com/user/sohohouse'
    profile2:
      profession: 'Buyer'
      industry: 'Beauty'
      city: 'New Jersey'
      about-me: 'Fantastic'
      chat: 'Anything'
      interest1: 'Ice skating'
      interest2: 'Inline skating'
      website: 'https://www.oops.org/'
      instagram: '@amazing'
      twitter: '@amazing'
      linkedin: 'https://linkedin.com/in/automtion'
      spotify: 'https://open.spotify.com/user/automation'
      youtube: 'https://www.youtube.com/user/automation'
  non-active-local: 'app.non.active.shw.local@example.com'
  non-active-every: 'app.non.active.every.local@example.com'
  active-local: 'app.active.shw.local@example.com'
  active-every: 'app.active.every.local@example.com'
  active-plus-local: 'app.active-plus.shw.local@example.com'
  active-plus-every: 'app.active-plus.every.local@example.com'
  active-members-only-status: 'ACTIVE MEMBERS ONLY'
  house-members-only-status: 'HOUSE MEMBERS ONLY'